typography_spectrum: 0.6275443052873015
color:
  brandStrength: 0.608733533648774
  lightness: 0.37390895653516054
  saturation: 0.6091158515773714
  rhythmicContrast: 0.4571439013816416
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
github: true
layout_spectrum: 0.6887090629898012
analytics:
  google: UA-81434823-1
author:
  email: wordpix@gmail.com
name: wordpix.in
title: Words.   Pictures.   Thoughts.
content: []
description: ''
url: 'https://thegrid.ai/wordpix/'
